# Generated by Django 6.0.3 on 2026-04-07 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('camera_source', models.CharField(default='0', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('total_frames', models.IntegerField(default=0)),
                ('total_blinks', models.IntegerField(default=0)),
                ('drowsy_events', models.IntegerField(default=0)),
                ('yawn_events', models.IntegerField(default=0)),
                ('avg_ear', models.FloatField(default=0.0)),
                ('avg_mar', models.FloatField(default=0.0)),
                ('avg_perclos', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('camera_source', models.CharField(default='0', help_text='0=webcam, rtsp://... , or video file path', max_length=500)),
                ('camera_width', models.IntegerField(default=640)),
                ('camera_height', models.IntegerField(default=480)),
                ('camera_fps', models.IntegerField(default=30)),
                ('camera_flip_horizontal', models.BooleanField(default=True)),
                ('ear_threshold', models.FloatField(default=0.22, help_text='EAR below this = eyes closed (Eq. 4)')),
                ('mar_threshold', models.FloatField(default=0.55, help_text='MAR above this = yawning (Section 2.5)')),
                ('drowsy_frame_threshold', models.IntegerField(default=15, help_text='Consecutive closed-eye frames -> DROWSY')),
                ('yawn_frame_threshold', models.IntegerField(default=10, help_text='Consecutive yawning frames -> YAWNING')),
                ('max_blink_frames', models.IntegerField(default=8, help_text='Max frames for a normal blink')),
                ('perclos_window_sec', models.FloatField(default=60.0, help_text='Time window (seconds) for PERCLOS')),
                ('perclos_threshold', models.FloatField(default=0.4, help_text='PERCLOS > 0.4 = high drowsiness risk')),
                ('alert_enabled', models.BooleanField(default=True)),
                ('alert_sound_file', models.CharField(blank=True, default='', max_length=500)),
                ('alert_cooldown_sec', models.FloatField(default=5.0)),
                ('alert_webhook_url', models.URLField(blank=True, default='')),
                ('gpu_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('state', models.CharField(choices=[('awake', 'Awake'), ('drowsy', 'Drowsy'), ('yawning', 'Yawning'), ('drowsy_yawning', 'Drowsy + Yawning'), ('falling_right', 'Falling Right'), ('falling_left', 'Falling Left'), ('falling_back', 'Falling Back'), ('no_face', 'No Face')], max_length=20)),
                ('ear_avg', models.FloatField(default=0)),
                ('mar', models.FloatField(default=0)),
                ('perclos', models.FloatField(default=0)),
                ('total_blinks', models.IntegerField(default=0)),
                ('head_roll', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('alert_number', models.IntegerField(default=0)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('sound_played', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.detectionsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('state', models.CharField(choices=[('awake', 'Awake'), ('drowsy', 'Drowsy'), ('yawning', 'Yawning'), ('drowsy_yawning', 'Drowsy + Yawning'), ('falling_right', 'Falling Right'), ('falling_left', 'Falling Left'), ('falling_back', 'Falling Back'), ('no_face', 'No Face')], max_length=20)),
                ('previous_state', models.CharField(blank=True, choices=[('awake', 'Awake'), ('drowsy', 'Drowsy'), ('yawning', 'Yawning'), ('drowsy_yawning', 'Drowsy + Yawning'), ('falling_right', 'Falling Right'), ('falling_left', 'Falling Left'), ('falling_back', 'Falling Back'), ('no_face', 'No Face')], max_length=20)),
                ('ear_left', models.FloatField(default=0)),
                ('ear_right', models.FloatField(default=0)),
                ('ear_avg', models.FloatField(default=0)),
                ('mar', models.FloatField(default=0)),
                ('perclos', models.FloatField(default=0)),
                ('head_roll', models.FloatField(default=0)),
                ('head_pitch', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('total_blinks', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='detection.detectionsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'state'], name='detection_d_session_bab457_idx')],
            },
        ),
    ]
