# Generated by Django 6.0.3 on 2026-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='gpu_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
